### ISSUE TITLE
Based on values of three angles determine that is it valid triangle or not

### ISSUE THREAD

**Issue by BT-ICD** [akshpatel24/ISGjstraining#10]
Based on the values of three angles determine that is it valid triangle or not

If the sum of all the angles is 180 then it is a valid triangle

**Comment by BT-ICD** [comment]
![image](https://github.com/akshpatel24/ISGjstraining/assets/61580782/9693a0f2-c718-4d80-9d61-0d33b5719dd8)

**Comment by akshpatel24** [comment]
done
